config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/home'

  get   'rsvp'    => 'rsvp#new'
  post  'rsvp'    => 'rsvp#create'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get   'request' => 'requests#new'
  post  'request' => 'requests#create'

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :details, presence: true
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  validates :names, presence: true
  validates :is_attending, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      flash[:success] = 'Thanks for getting involved!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    def request_params
      params.require(:request).permit(:from, :details)
    end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  def new
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      flash[:success] = 'Thanks for letting us know if you are coming!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def rsvp_params
      params.require(:rsvp).permit(:names, :is_attending, :comments)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  ENTRY_PASSWORD = ENV['ENTRY_PASSWORD']

  def new
  end

  def create
    password = params[:session][:password]
    if password && password == ENTRY_PASSWORD
      sign_in
      flash[:success] = 'Thanks for getting involved!'
      redirect_to root_path
    else
      flash[:danger] = 'Invalid password'
      redirect_to root_path
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    cookies.permanent[:has_access] = true
  end

  def sign_out
    cookies.delete(:has_access)
  end

  def has_access?
    cookies[:has_access]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.haml
- if has_access?
  .navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      .navbar-collapse.collapse#target-nav
        %ul.nav.navbar-nav.navbar-right.nav-home
          - if controller.controller_name == "static_pages" && controller.action_name == "home"
            %li.active= link_to "Venue", "#venue"
            %li= link_to "Places to stay", "#accomodation"
            %li= link_to "Attire", "#attire"
            %li= link_to "Songs Requests", "#requests"
          - else
            %li= link_to 'home', root_path
          - if Rails.env.development? && has_access?
            %li= link_to 'logout', logout_path, method: "delete"

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Alice and Abhi 27th June 2015
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
    = csrf_meta_tags
    = render 'layouts/shim'
    = render 'layouts/header'
  %body{"data-spy" => "scroll", "data-target" => "#target-nav", "data-offset" => "70"}
    .container-fluid.body-content
      = render 'shared/flash_messages'
      = yield
    = debug(params) if Rails.env.development?

app/views/requests/new.html.haml
.row
  .col-cs-12.col-sm-12.col-md-12
    %h1 Song Requests
    %p Let us know what you like and we'll see if we can fit it into the playlist.
  .col-xs-12.col-sm-6.col-sm-offset-1.col-md-6.col-md-offset-1
    = form_for(@request, url: request_path) do |f|
      = render 'shared/error_messages', object: @request
      .form-group
        %label.control-label{:for => "requestInputFrom"} From
        %input#requestInputFrom.form-control{:placeholder => "Tell us who the request is from", :type => "text", :name => "request[from]"}
      .form-group
        %label.control-label{:for => "requestInputDetails"} Requests
        %textarea#requestInputDetails.form-control{:placeholder => "Please include song title and singer/band", :type => "text", :name => "request[details]", :rows => 5}
      = f.submit "Submit", class: 'btn btn-general'

app/views/rsvp/new.html.haml
.row
  .col-cs-12.col-sm-12.col-md-12
    %h1 RSVP
    %p Let us know if you're coming along.
  .col-xs-12.col-sm-6.col-sm-offset-1.col-md-6.col-md-offset-1
    = form_for(@rsvp, url: rsvp_path) do |f|
      = render 'shared/error_messages', object: @rsvp
      .form-group
        .radio
          %label
            %input#optionsRadios1{:checked => "", :name => "rsvp[is_attending]", :type => "radio", :value => "true"}
              Attending
        .radio
          %label
            %input#optionsRadios2{:name => "rsvp[is_attending]", :type => "radio", :value => "false"}
              Not Attending
      .form-group
        %label.control-label{:for => "rsvpInputNames"} Names
        %input#rsvpInputNames.form-control{:placeholder => "Comma separated list of people that are or are not coming", :type => "text", :name => "rsvp[names]"}
      .form-group
        %label.control-label{:for => "rsvpInputComments"} Comments
        %textarea#rsvpInputComments.form-control{:placeholder => "E.g. Let us know if anyone is intollerant or allergic to anything or you can only make part of the day.", :type => "text", :name => "rsvp[comments]", :rows => 5}
      = f.submit "Submit", class: 'btn btn-general'

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_messages.html.haml
.row
  .col-xs-12.col-sm-12.col-md-12
    - flash.each do |type, message|
      %div{:class => "alert alert-#{type} fade in"}
        %button.close{"data-dismiss" => "alert"} ×
        = message

app/views/static_pages/_logged_in_home.html.haml
.row
  .col-md-12
    %h3#venue
      Venue
.row
  .col-xs-12.col-sm-10.col-md-10.center-block
    #venue-map
.row
  .col-md-12
    %h3#accomodation
      Places to stay
    %p
      Northbrook Park has accommodation on site that can sleep up to 80 people, and can be booked either as individual rooms or the whole cottage (sleeping 8).
      Unfortunately this accommodation is only available on the Saturday night.
      Bookings can be made directly with Central Reservations on 0844 824777. See
      = link_to "here", "http://www.northbrookparkmews.co.uk/"
      for more information.

      There are a number of other hotels in Farnham and the surrounding area that you can stay in.
      On the Friday night Abhi will be staying
      = link_to "here", "http://www.mercure.com/gb/hotel-6621-mercure-farnham-bush-hotel/index.shtml", target: "_blank"
      and Alice will be staying
      = link_to "here", "http://www.bishopstable.com/index.htm", target: "_blank"
      \. You are welcome to join us at either and raise a glass with us ahead of the wedding day.
      We will update the site with where we plan to spend the evening.

      The other hotels in the area are:
    %p= link_to "1 Park Row", "http://1parkrow.co.uk/", target: "_blank"
    %p= link_to "Best Western", "http://www.bestwestern.co.uk/hotels/frensham-pond-hotel-farnham-83620/hotel-info/default.aspx", target: "_blank"
    %p= link_to "Farnham House Hotel", "http://www.farnhamhousehotel.com/bedrooms/", target: "_blank"
    %p= link_to "Hotel de Vie", "http://www.hoteldevie.com/", target: "_blank"
    %p= link_to "The Princess Royal", "http://www.theprincessroyal.co.uk/bedrooms", target: "_blank"
.row
  .col-xs-12.col-sm-12.col-md-12
    %h3#attire
      Attire
    %p
      There is no rule for what you need to wear to the wedding.
      Traditional British, Indian, a mix of the two or any other type of wedding wear is fine. 
      You can wear the same thing through the day or feel free to change for the different ceremonies.
      There'll be places to change at the wedding location for men and women.
      We've included what we are planning to do below.
    %h4
      Morning Civil Ceremony
    %p
      British wedding style.
    %h4
      Afternoon Indian Ceremony
    %p
      Indian wedding style.
    %p
      See
      = link_to "here", "http://www.kalkifashion.com/blogs/different-types-of-indian-wedding-dresses", target: "_blank"
      for different types of women's fashion. Alice will be in a red wedding lehenga. Red is a traditional colour for the bride so please stay away
      from that colour. Salwar Kameez or Lengha are a good choice if you want something easy to wear. Chaniya Choli is similar to Lengha so
      you can mention that as well if you are looking for those types of clothing.
      Sarees are also an option but require a bit more work to wear and can be more expensive.
    %p
      See
      = link_to "here", "http://www.indianweddingsaree.com/static/Mens-Wear.aspx", target: "_blank"
      for different types of men's fashion. Abhi will be in a white wedding sherwani. White is a traditional colour for the groom so please stay away
      from that colour as well. Kurta pyjamas are a good choice if you want something easy to wear.
      Indo western suits and sherwanis are also an option but can be more expensive.
    %h4
      Evening Reception
    %p
      We'll most likely stick with our Indian clothes or switch back to our British clothes later on in the night. Feel free to do the same or get a
      third outfit! Whatever you decide make sure you can dance in it :)
.row
  .col-xs-12.col-sm-12.col-md-12
    %h3#requests
      Song Requests
    %p
      Let us know songs you'd like on the playlist.
    = link_to "Requests", request_path , class: "btn btn-primary btn-general"

app/views/static_pages/_logged_out_home.html.haml
.row
  .col-xs-12.col-sm-6.col-md-6.picture-col.light-bg
    .row
      .col-md-12.text-center
        %h1
          Alice & Abhi
    .row
      .col-md-12
        = image_tag 'background/jersey.jpg', class: 'img-responsive frame'
  .col-xs-12.col-sm-6.col-md-6.login-input-col.dark-bg
    .row#login-input
      = form_for(:session, url: login_path) do |f|
        .col-xs-6.col-sm-6.col-sm-offset-1.col-md-6.col-md-offset-1
          = f.text_field :password, placeholder: 'Enter password', class: 'form-control'
        .col-xs-6.col-sm-5.col-md-5
          = f.submit "Enter", class: 'btn btn-general'

app/views/static_pages/home.html.haml
- if has_access?
  = render "logged_in_home"
- else
  = render "logged_out_home"